### ISSUE TITLE
Extend databroker-unpack to load documents into Mongo

### ISSUE THREAD

**Issue by danielballan** [bluesky/databroker-pack#7]
For many use cases, running intake top of a directory of `mspgack` or `jsonl` files is not suitable. The `databroker-unpack` utility should provide an option to copy Documents from the files into MongoDB and auto-generate a suitable catalog file.

I didn't do this in the first pass because it was not obvious to me how to spell, or how we might want to extend it. Initial thought:

```
databroker-unpack inplace DIRECTORY NEW_CATALOG_NAME  # current functionality
```
and

```
databroker-unpack mongo_normalized DIRECTORY NEW_CATALOG_NAME --metadatastore=MONGO_URI --filestore=MONGO_URI
```

Now, `databroker-pack` is intentionally "opinionated" and only supports a hard-coded subset of suitcases (msgpack, jsonl). Should we do the same for `-unpack`? I think so, because it enables us to auto-generate a working catalog file.

**Comment by tacaswell** [comment]
Maybe a `--merge` flag that will try to insert into an existing catalog (rather than creating a new one).  You can imagine having behind the scenes logic to sort out if we can side-load (ex msgpack -> msgpack) by just copy files, but fallback to `db_new.insert(...)`.

We probably need a set of helpers for creating new catalogs (of what ever backing) and dumping the config files in the correct place.

**Comment by danielballan** [comment]
Both done in #16
